version: '3'
services:
  prometheus:
    image: prom/prometheus:v2.30.3
    ports:
      - 9090:9090
    volumes:
      - ./prometheus:/etc/prometheus
      - prometheus-data:/prometheus
    command: --web.enable-lifecycle  --config.file=/etc/prometheus/prometheus.yml
  grafana:
    image: grafana/grafana 
    ports:
      - '3000:3000'
    volumes:
      - ./grafana/provisioning/datasources:/etc/grafana/provisioning/datasources
      - ./grafana/provisioning/dashboards:/etc/grafana/provisioning/dashboards   

      - grafana-data:/var/lib/grafana
    depends_on:
      - prometheus      
    environment:      
      - GF_SECURITY_ADMIN_PASSWORD=admin
  microservice-map-info:    
    build: 
     context: microservice-map-info
     dockerfile: Dockerfile
    ports:
      - 80:80     
volumes:
  prometheus-data:
  grafana-data:



